# Docs are in https://github.com/syself/csi-topolvm/pull/3

image:
  # image.repository -- TopoLVM image repository to use.
  repository: ghcr.io/syself/csi-topolvm-with-sidecar

  # image.tag -- TopoLVM image tag to use.
  # @default -- `{{ .Chart.AppVersion }}`
  tag: dev-attach # 0.18.1

  # image.pullPolicy -- TopoLVM image pullPolicy.
  pullPolicy:  # Always

  csi:
    # image.csi.csiAttacher -- Specify csi-attacher image.
    # If not specified, `ghcr.io/topolvm/topolvm-with-sidecar:{{ .Values.image.tag }}` will be used.
    csiAttacher: registry.k8s.io/sig-storage/csi-attacher:v4.5.1

lvmd:
  # lvmd.deviceClasses -- Specify the device-class settings.
  deviceClasses:
    - name: ssd
      volume-group: myvg1
      default: true
      spare-gb: 10


  # lvmd.nodeSelector -- Specify nodeSelector.
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  nodeSelector:
    instance.hetzner.cloud/is-root-server: "true"

# CSI node service
node:
  # node.nodeSelector -- Specify nodeSelector.
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  nodeSelector:
    instance.hetzner.cloud/is-root-server: "true"

# CSI controller service
controller:
  # controller.replicaCount -- Number of replicas for CSI controller service.
  replicaCount: 1 # during development

  nodeFinalize:
    # controller.nodeFinalize.skipped -- Skip automatic cleanup of PhysicalVolumeClaims when a Node is deleted.
    skipped: true
