apiVersion: v2
type: application

home: https://github.com/topolvm/topolvm
name: topolvm
description: Topolvm
version: 14.1.2
appVersion: 0.29.0
sources:
  - https://github.com/topolvm/topolvm

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.7.0
    condition: cert-manager.enabled

annotations:
  artifacthub.io/images: |
    - name: topolvm-with-sidecar
      image: ghcr.io/topolvm/topolvm-with-sidecar:0.29.0
    - name: topolvm-with
      image: ghcr.io/topolvm/topolvm:0.29.0
  artifacthub.io/license: Apache-2.0
